/** @format */

const base = [
  {
    category: 'Стиральная машина',
    manufacturer: 'LG',
    model: 'F1096TD3',
    features: ['с прямым приводом', 'с отжимом'],
    type: 'компактные',
    steamTreatment: false,
    motorType: 'инверторный',
    width: 60,
    depth: 55,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1000,
    maximumLoad: 8,
    rating: 3.9,
    price: 35990,
    photo: '1486652781.0764',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'LG',
    model: 'F1296TD4',
    features: ['с прямым приводом', 'с отжимом'],
    type: 'компактные',
    steamTreatment: false,
    motorType: 'инверторный',
    width: 60,
    depth: 55,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Серебристый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 8,
    rating: 1.8,
    price: 27990,
    photo: '1571061784.8957',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'LG',
    model: 'F10B8MD',
    features: ['под раковину', 'с прямым приводом', 'с отжимом'],
    type: 'узкие',
    steamTreatment: false,
    motorType: 'инверторный',
    width: 60,
    depth: 44,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1000,
    maximumLoad: 5,
    rating: 1.0,
    price: 22900,
    photo: '52102-0',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'LG',
    model: 'F80B8LD6',
    features: ['с прямым приводом', 'с отжимом'],
    type: 'полногабаритные',
    steamTreatment: false,
    motorType: 'инверторный',
    width: 60,
    depth: 44,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 800,
    maximumLoad: 5,
    rating: 3.4,
    price: 21900,
    photo: '1581516918.966',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'LG',
    model: 'F1296HDS4',
    features: ['с прямым приводом', 'с отжимом'],
    type: 'полногабаритные',
    steamTreatment: true,
    motorType: 'инверторный',
    width: 60,
    depth: 44,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Серебристый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 7,
    rating: 5.0,
    price: 27619,
    photo: '1581516948.3491',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'CANDY',
    model: 'CS4 1051D1/2-07',
    features: ['под раковину', 'с отжимом'],
    type: 'узкие',
    steamTreatment: false,
    motorType: 'коллекторный',
    width: 60,
    depth: 40,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: false,
    spinSpeed: 1000,
    maximumLoad: 5,
    rating: 4.7,
    price: 15039,
    photo: '1495443022.4217',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'CANDY',
    model: 'CS4 1051D1/3-07',
    features: ['под раковину', 'с отжимом'],
    type: 'узкие',
    steamTreatment: false,
    motorType: 'коллекторный',
    width: 60,
    depth: 40,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: false,
    spinSpeed: 1000,
    maximumLoad: 5,
    rating: 4.7,
    price: 15039,
    photo: '1495443022.4217',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'CANDY',
    model: 'CSWS40 364D/2-07',
    features: ['с сушкой', 'с отжимом'],
    type: 'полногабаритные',
    steamTreatment: false,
    motorType: 'коллекторный',
    width: 60,
    depth: 44,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1300,
    maximumLoad: 6,
    rating: 4.3,
    price: 25740,
    photo: '1542569563.2641',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'CANDY',
    model: 'GVSW 4364TWHC-07',
    features: ['с отжимом'],
    type: 'полногабаритные',
    steamTreatment: false,
    motorType: 'коллекторный',
    width: 60,
    depth: 44,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1300,
    maximumLoad: 6,
    rating: 4.4,
    price: 28888,
    photo: '1507974275.2499',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'CANDY',
    model: 'GVS4 127TWC3/2-07',
    features: ['с отжимом'],
    type: 'полногабаритные',
    steamTreatment: true,
    motorType: 'коллекторный',
    width: 60,
    depth: 43,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 7,
    rating: 4.8,
    price: 20776,
    photo: '1596006921.9596',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'Samsung',
    model: 'WW65K42E00SDLP',
    features: ['с отжимом', 'добавление белья после старта'],
    type: 'компактные',
    steamTreatment: true,
    motorType: 'инверторный',
    width: 60,
    depth: 45,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Серебристый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 6,
    rating: 3.8,
    price: 27091,
    photo: '1491831488.7448',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'Samsung',
    model: 'WW70T3020BS',
    features: ['с отжимом'],
    type: 'полногабаритные',
    steamTreatment: false,
    motorType: 'стандартный',
    width: 59.5,
    depth: 44,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Серебристый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 7,
    rating: 4.9,
    price: 20148,
    photo: '1611036908.6554',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'Samsung',
    model: 'WF60F1R0H0W',
    features: ['с отжимом'],
    type: 'компактные',
    steamTreatment: false,
    motorType: 'коллекторный',
    width: 60,
    depth: 45,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 6,
    rating: 5.0,
    price: 25668,
    photo: '307169-0',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'Samsung',
    model: 'WF60F1R0E2W',
    features: ['с отжимом'],
    type: 'компактные',
    steamTreatment: false,
    motorType: 'коллекторный',
    width: 60,
    depth: 45,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 6,
    rating: 4.4,
    price: 21465,
    photo: '375910-0',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'Samsung',
    model: 'WW80R42LHDW',
    features: ['с отжимом'],
    type: 'полногабаритные',
    steamTreatment: true,
    motorType: 'инверторный',
    width: 60,
    depth: 45,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 8,
    rating: 4.7,
    price: 27456,
    photo: '1596694510.0077',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'INDESIT',
    model: 'BWSA 51051 1',
    features: ['под раковину', 'с отжимом'],
    type: 'узкие',
    steamTreatment: false,
    motorType: 'коллекторный',
    width: 60,
    depth: 42.5,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: false,
    spinSpeed: 1000,
    maximumLoad: 5,
    rating: 5.0,
    price: 13590,
    photo: '1475740840.4895',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'INDESIT',
    model: 'IWC 6105 B',
    features: ['с отжимом'],
    type: 'компактные',
    steamTreatment: false,
    motorType: 'коллекторный',
    width: 60,
    depth: 55,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: false,
    spinSpeed: 1000,
    maximumLoad: 6,
    rating: 2.4,
    price: 20247,
    photo: '75656-0',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'INDESIT',
    model: 'IWC 6105 C',
    features: ['с отжимом'],
    type: 'компактные',
    steamTreatment: false,
    motorType: 'коллекторный',
    width: 60,
    depth: 55,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: false,
    spinSpeed: 1000,
    maximumLoad: 6,
    rating: 4.5,
    price: 20247,
    photo: '75656-0',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'INDESIT',
    model: 'XWDE 861480X W',
    features: ['с сушкой', 'с отжимом'],
    type: 'полногабаритные',
    steamTreatment: false,
    motorType: 'коллекторный',
    width: 60,
    depth: 60,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1400,
    maximumLoad: 8,
    rating: 4.7,
    price: 53259,
    photo: '83028-0',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'INDESIT',
    model: 'BWE 81282 L',
    features: ['с отжимом'],
    type: 'полногабаритные',
    steamTreatment: false,
    motorType: 'инверторный',
    width: 59.5,
    depth: 54,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 8,
    rating: 4.3,
    price: 29224,
    photo: '1616750122.3281',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'Haier',
    model: 'HW60-1229AS',
    features: ['с отжимом'],
    type: 'компактные',
    steamTreatment: true,
    motorType: 'коллекторный',
    width: 60,
    depth: 45,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Серебристый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 6,
    rating: 3.5,
    price: 25990,
    photo: '1520740244.3097',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'Haier',
    model: 'HW70-BP1439G',
    features: ['с отжимом'],
    type: 'полногабаритные',
    steamTreatment: true,
    motorType: 'инверторный',
    width: 60,
    depth: 45,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Золотистый',
    displayAvailability: true,
    spinSpeed: 1400,
    maximumLoad: 7,
    rating: 3.2,
    price: 35437,
    photo: '1577964103.0758',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'Haier',
    model: 'HW60-BP12959B',
    features: ['с отжимом'],
    type: 'полногабаритные',
    steamTreatment: true,
    motorType: 'инверторный',
    width: 60,
    depth: 41,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 6,
    rating: 5.0,
    price: 31149,
    photo: '1592813051.7135',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'Haier',
    model: 'HWD120-B1558U',
    features: ['с прямым приводом', 'с отжимом', 'с управлением со смартфона'],
    type: 'полногабаритные',
    steamTreatment: false,
    motorType: 'инверторный',
    width: 60,
    depth: 60,
    height: 99,
    typeOfUpload: 'фронтальная',
    color: 'Белый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 12,
    rating: 4.9,
    price: 117719,
    photo: '1544546010.5529',
  },
  {
    category: 'Стиральная машина',
    manufacturer: 'Haier',
    model: 'HW60-BP12959BS',
    features: ['с отжимом'],
    type: 'полногабаритные',
    steamTreatment: true,
    motorType: 'инверторный',
    width: 60,
    depth: 41,
    height: 85,
    typeOfUpload: 'фронтальная',
    color: 'Серебристый',
    displayAvailability: true,
    spinSpeed: 1200,
    maximumLoad: 6,
    rating: 5.0,
    price: 33099,
    photo: '1592813052.4488',
  },
];

